apiVersion: v1
kind: Service
metadata:
  namespace: appraisal
  labels:
    app: db
  name: db
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: appraisal
  labels:
    app: db
  name: db
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - image: mysql:5.7
          name: db
          env:
            - name: MYSQL_DATABASE
              value: 'appraisal-sheet-mysql'
            - name: MYSQL_PASSWORD
              value: 'root'
            - name: MYSQL_ROOT_PASSWORD
              value: 'root'
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv-volume
  namespace: appraisal
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/srv/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: appraisal
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
