apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: appraisal
  labels:
    app: nginx
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30002
  selector:
    app: nginx
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: appraisal
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
        - name: "regsecret"
      containers:
        - name: rprx
          image: ncdocker.netconomy.net/msgnc/app/rprx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      nodeSelector:
        proxy: "true"
